version: '3.8'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    restart: unless-stopped
    networks:
      - perplexica_network
    ports:
      - "8080:8080"  # Added port mapping for SearxNG

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    volumes:
      - backend-dbstore:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    networks:
      - perplexica_network
    environment:
      - PORT=3001
    ports:
      - "3001:3001"  # Explicitly map backend port

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://fcoco404048oso8gc04k044k.159.69.19.216.sslip.io:3001/api
        - NEXT_PUBLIC_WS_URL=ws://fcoco404048oso8gc04k044k.159.69.19.216.sslip.io:3001
    depends_on:
      - perplexica-backend
    restart: unless-stopped
    networks:
      - perplexica_network
    ports:
      - "3000:3000"  # Map frontend port
    environment:
      - PORT=3000  # Explicitly set frontend port

networks:
  perplexica_network:
    driver: bridge

volumes:
  backend-dbstore:
